### ISSUE TITLE
ActiveRecordCheck fails with a TypeError

### ISSUE THREAD

**Issue by stanishev** [envylabs/rapporteur#12]
Hello @nbibler, 
in active_record_check.rb, 

ActiveRecord::Base.connection.execute("SELECT current_time AS time").first.fetch("time")
fails with a <TypeError: no implicit conversion of String into Integer> because .first returns an array and not a hash (as it seems to expect).

Presumably this is working for you or other users, but I am puzzled how..

**Comment by nbibler** [comment]
Good question. I can't say I actually use that check anywhere. I mostly just use the revision and time.  I'll take a look at it tonight and see what happened…

**Comment by nbibler** [comment]
Hmm.. I'm not seeing errors in my local testing. PostgreSQL both appear to be working as expected. And presumably sqlite3 works as expected since that is the db under test.

With a Rails + pg app:

```
Started GET "/status.json" for ::1 at 2017-01-11 12:45:42 -0500
  ActiveRecord::SchemaMigration Load (0.7ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by StatusesController#show as JSON
   (0.6ms)  SELECT current_time AS time
Completed 200 OK in 15ms (Views: 5.2ms | ActiveRecord: 0.6ms | Elasticsearch: 0.0ms)
```

Now, exercising that the database is offline to see if it shows an error is a bit trickier. Rails isn't happy at all when you remove the database from behind it. For example, in that Rails + pg app, I get `PG::Error (invalid encoding name: utf8)` exceptions thrown long before Rapporteur gets to run stemming from an Active::Record `checkout_and_verify` call in the middleware stack.

As I mentioned earlier, I don't use that check in any applications. In practice, Rails explodes loudly when the database connections are broken and I have other exception collection mechanisms in place to become alerted to it.

**Comment by stanishev** [comment]
Hi Nathaniel, 

Thank you for the info. Since the only thing we have different is the database type (we're on mysql) I went googling a bit about this and stumbled on this (see the side note on records_array in the answer):

http://stackoverflow.com/questions/14824453/rails-raw-sql-example

I am a bit new to the RoR world to make complete sense of it, but from digging into the docs a bit it does seem that Mysql2::Result and PG::Result are just... different. 

Also looking at the documentation for the **execute** method: http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html#method-i-execute

it states that the execute method does return the _raw result from the connection adapter_, and the documentation does suggest using the **exec_query** method instead. 

So I tried exec_query with postgres and mysql (but not for sqlite3) and it does seem to work better, the return type is a nice ActiveRecord::Result for both adapters, and using the ..first.fetch("time") syntax works for both.

Would you be ok with a change to active_record_check.rb to use exec_query? (I suspect most people using this gem opt for adding custom checks anyway, which steps around this problem, but it might make the gem a bit more friendly to future newbies looking into it).

**Comment by nbibler** [comment]
@stanishev: I pushed an update to use `select_value` rather than `execute`. This should fix your issue. I haven't released a new version yet but you can pull the library from the gif ref in the commit above this message (5c95ef4). Let me know if that works better for you.
